### ISSUE TITLE
visualization/README.md - troubleshooting access to /place when running docker on MacOS

### ISSUE THREAD

**Issue by carolinarr** [DevinBayly/vis-seive#1]
In visualization/README.md files, under "Setup Docker container" section, I was unable to get access to /place when following setup instructions for MacOS.

I found I could get access to a "place" directory within the container if I:
1. created $(pwd)/place directory beforehand
2. and then ran `docker run -it --rm --mount type=bind,source="$(pwd)",target=/place -p 8080:8080 continuumio/miniconda3`

Once inside the container, I navigated to /place, and could see all the content from $pwd within it. 

Does this accomplish what we're looking for here? 

(*Note for myself, used this to troubleshoot command: https://docs.docker.com/storage/bind-mounts/#start-a-container-with-a-bind-mount*)

**Comment by DevinBayly** [comment]
Sounds like that's a yes, the goal is to just see the $pwd content in the `/place` folder. If you have that then you're golden!

Cheers. I'll update the instructions
